"""Add user in Donation

Revision ID: 04
Revises: 03
Create Date: 2024-02-03 17:02:02.817683

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04'
down_revision = '03'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('donation', schema=None) as batch_op:
        batch_op.create_foreign_key(
            'fk_reservation_user_id_user',
            'user',
            ['user_id'],
            ['id']
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('donation', schema=None) as batch_op:
        batch_op.drop_constraint(
            'fk_reservation_user_id_user',
            type_='foreignkey'
        )

    # ### end Alembic commands ###
